### ISSUE TITLE
How to retransmit any of the received codes?

### ISSUE THREAD

**Issue by yashverma** [sebmillet/RF433any#13]
On running the examples I get an output like the following.

Received 39 bits (x2): 28 C8 C5 80 88
Received 32 bits (x1): 51 91 8B 01
Received 39 bits (x2): 28 C8 C5 80 88
Received 32 bits (x1): 51 91 8B 01
Received 39 bits (x1): 28 C8 C5 80 8F

I have no idea how to retransmit those using a rf433 modules , is there a arduino library that can retransmit this ?

**Comment by sebmillet** [comment]
Hello

RF433any does not allow to retransmit anything.
You got to use rf433send to do so. It is here: https://github.com/sebmillet/rf433send

In RF433any, you should use an example where the code output is close to the one you need to retransmit.
See for example https://github.com/sebmillet/RF433any/blob/ce6e960758bd1f58f90a386bf0b92b5f4c148e33/examples/01_main/01_main.ino

Note RF433any's output is meant for rf433recv not rf433send.
You'll have to adjust RF433any's output a little bit so that it fits with rf433send requirements.

Regards, Sébastien Millet

**Comment by yashverma** [comment]
Oh,  hi.  Huge thanks for replying . I found the send library the other
day. Everything works as expected now.

Thanks for your hard work
